PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  ?predicate ?a ?b ; a rdf:Property .
  ?concept   ?c ?d ; a rdfs:Class .
} 
FROM <http://example.org/contacts_b>
FROM <http://example.org/contacts_a>
WHERE {
  { 
    {SELECT DISTINCT ?predicate {[] ?predicate []}} 
    OPTIONAL { ?predicate ?a ?b } 
  }	UNION { 
    {SELECT DISTINCT ?concept {[] a ?concept   }} 
    OPTIONAL { ?concept ?c ?d } 
  }
} 